name: CI

on: [push, pull_request]

jobs:
    ci:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                php-versions: ['8.1']

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
            -   run: composer install
            -   run: make ci
            -   run: bash <(curl -s https://codecov.io/bash) -f "build/coverage.xml" -t ${{ secrets.CODECOV_TOKEN }}
